services:
  - type: worker
    name: queue
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A humblebee worker -l info -P eventlet"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: humblebee
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn humblebee.wsgi:application"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: singapore
    plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
